name: Integrations (Swift)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: docker-compose run integration_swift

      - name: Cleanup
        if: always()
        run: docker-compose down
